version: 2
jobs:
  build:
    docker:
      - image: alpine:edge
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            apk add --no-cache shellcheck
      - run:
          name: Shellcheck
          command: shellcheck scripts/*
